name: video
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Para reproducir los videos
  video_player: ^2.10.0

  # Brinda controles de UI listos para el video_player
  chewie: ^1.13.0
  # Para seleccionar la carpeta (funciona en móvil y escritorio)
  file_picker: ^10.3.3
  # Para guardar la ruta de la carpeta (preferencias)
  shared_preferences: ^2.5.3
  # Para manejar permisos en Android/iOS
  permission_handler: ^12.0.1
  # Para obtener la ruta de los archivos (aunque file_picker a veces lo incluye)
  path_provider: ^2.1.5
  # Para saber la versión del SDK de Android
  device_info_plus: ^12.2.0
  # Para Picture-in-Picture
  pip_view: ^0.9.7
  # Colores dinámicos (Material You)
  dynamic_color: ^1.8.1
  # Miniaturas de video nativas
  fc_native_video_thumbnail: ^0.17.2
  # Estado y gestión
  provider: ^6.1.5+1
  # Efecto shimmer para placeholders
  shimmer: ^3.0.0
  # Evitar que la pantalla se apague durante la reproducción de video
  wakelock_plus: ^1.4.0
  # Control de volumen del dispositivo
  volume_controller: ^2.0.3
  # Control del brillo de la pantalla
  screen_brightness: 2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
